// Generated by scripts/build-app.mjs
const CACHE = 'hcr-shell-507023b10b';
const BASE = "/havenwear-radar/";
const SHELL = ["/havenwear-radar/","/havenwear-radar/index.html","/havenwear-radar/manifest.webmanifest","/havenwear-radar/favicon.svg","/havenwear-radar/theme.js","/havenwear-radar/assets/app-a2be19d6f9.js","/havenwear-radar/assets/app-11ce21c6c8.css","/havenwear-radar/assets/worker-68c256837a.js","/havenwear-radar/assets/sql-wasm-38c14f6e37.wasm","/havenwear-radar/icons/icon-192.png","/havenwear-radar/icons/icon-512.png","/havenwear-radar/icons/apple-touch-icon.png"];
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('hcr-shell-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const u = new URL(e.request.url);
  if (e.request.method !== 'GET' || u.origin !== self.location.origin || !u.pathname.startsWith(BASE)) return;
  if (e.request.mode === 'navigate') {
    e.respondWith(fetch(e.request).catch(() => caches.match(BASE + 'index.html')));
    return;
  }
  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request)));
});
